# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from dal.v1 import dal_pb2 as dal_dot_v1_dot_dal__pb2


class DataAccessServiceStub(object):
    """─── Service Definition ────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/dal.v1.DataAccessService/Query',
                request_serializer=dal_dot_v1_dot_dal__pb2.QueryRequest.SerializeToString,
                response_deserializer=dal_dot_v1_dot_dal__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/dal.v1.DataAccessService/Write',
                request_serializer=dal_dot_v1_dot_dal__pb2.WriteRequest.SerializeToString,
                response_deserializer=dal_dot_v1_dot_dal__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.BatchWrite = channel.stream_stream(
                '/dal.v1.DataAccessService/BatchWrite',
                request_serializer=dal_dot_v1_dot_dal__pb2.BatchWriteRequest.SerializeToString,
                response_deserializer=dal_dot_v1_dot_dal__pb2.BatchWriteResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/dal.v1.DataAccessService/Subscribe',
                request_serializer=dal_dot_v1_dot_dal__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=dal_dot_v1_dot_dal__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.IngestStream = channel.stream_stream(
                '/dal.v1.DataAccessService/IngestStream',
                request_serializer=dal_dot_v1_dot_dal__pb2.IngestStreamRequest.SerializeToString,
                response_deserializer=dal_dot_v1_dot_dal__pb2.IngestStreamResponse.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/dal.v1.DataAccessService/Check',
                request_serializer=dal_dot_v1_dot_dal__pb2.CheckRequest.SerializeToString,
                response_deserializer=dal_dot_v1_dot_dal__pb2.CheckResponse.FromString,
                _registered_method=True)


class DataAccessServiceServicer(object):
    """─── Service Definition ────────────────────────────────

    """

    def Query(self, request, context):
        """Synchronous CRUD
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchWrite(self, request_iterator, context):
        """Bidirectional streaming: batch writes with per-item responses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Server streaming: subscribe to entity change events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestStream(self, request_iterator, context):
        """Bidirectional streaming: high-throughput data ingestion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataAccessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=dal_dot_v1_dot_dal__pb2.QueryRequest.FromString,
                    response_serializer=dal_dot_v1_dot_dal__pb2.QueryResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=dal_dot_v1_dot_dal__pb2.WriteRequest.FromString,
                    response_serializer=dal_dot_v1_dot_dal__pb2.WriteResponse.SerializeToString,
            ),
            'BatchWrite': grpc.stream_stream_rpc_method_handler(
                    servicer.BatchWrite,
                    request_deserializer=dal_dot_v1_dot_dal__pb2.BatchWriteRequest.FromString,
                    response_serializer=dal_dot_v1_dot_dal__pb2.BatchWriteResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=dal_dot_v1_dot_dal__pb2.SubscribeRequest.FromString,
                    response_serializer=dal_dot_v1_dot_dal__pb2.SubscribeResponse.SerializeToString,
            ),
            'IngestStream': grpc.stream_stream_rpc_method_handler(
                    servicer.IngestStream,
                    request_deserializer=dal_dot_v1_dot_dal__pb2.IngestStreamRequest.FromString,
                    response_serializer=dal_dot_v1_dot_dal__pb2.IngestStreamResponse.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=dal_dot_v1_dot_dal__pb2.CheckRequest.FromString,
                    response_serializer=dal_dot_v1_dot_dal__pb2.CheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dal.v1.DataAccessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dal.v1.DataAccessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataAccessService(object):
    """─── Service Definition ────────────────────────────────

    """

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dal.v1.DataAccessService/Query',
            dal_dot_v1_dot_dal__pb2.QueryRequest.SerializeToString,
            dal_dot_v1_dot_dal__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dal.v1.DataAccessService/Write',
            dal_dot_v1_dot_dal__pb2.WriteRequest.SerializeToString,
            dal_dot_v1_dot_dal__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchWrite(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/dal.v1.DataAccessService/BatchWrite',
            dal_dot_v1_dot_dal__pb2.BatchWriteRequest.SerializeToString,
            dal_dot_v1_dot_dal__pb2.BatchWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dal.v1.DataAccessService/Subscribe',
            dal_dot_v1_dot_dal__pb2.SubscribeRequest.SerializeToString,
            dal_dot_v1_dot_dal__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/dal.v1.DataAccessService/IngestStream',
            dal_dot_v1_dot_dal__pb2.IngestStreamRequest.SerializeToString,
            dal_dot_v1_dot_dal__pb2.IngestStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dal.v1.DataAccessService/Check',
            dal_dot_v1_dot_dal__pb2.CheckRequest.SerializeToString,
            dal_dot_v1_dot_dal__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
