# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dal/v1/shop.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'dal/v1/shop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61l/v1/shop.proto\x12\x06\x64\x61l.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x02\n\x12ShopifyCustomerMap\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n\x0b\x63ustomer_id\x18\x02 \x01(\tR\ncustomerId\x12.\n\x13shopify_customer_id\x18\x03 \x01(\tR\x11shopifyCustomerId\x12#\n\rshopify_email\x18\x04 \x01(\tR\x0cshopifyEmail\x12\x37\n\tsynced_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x08syncedAt\x12\x39\n\ncreated_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\"\xca\x02\n\x0fWebhookEventLog\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12,\n\x12shopify_webhook_id\x18\x02 \x01(\tR\x10shopifyWebhookId\x12\x14\n\x05topic\x18\x03 \x01(\tR\x05topic\x12.\n\x13shopify_resource_id\x18\x04 \x01(\tR\x11shopifyResourceId\x12!\n\x0cpayload_json\x18\x05 \x01(\tR\x0bpayloadJson\x12\x16\n\x06status\x18\x06 \x01(\tR\x06status\x12=\n\x0cprocessed_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0bprocessedAt\x12\x39\n\ncreated_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAtB\x85\x01\n\ncom.dal.v1B\tShopProtoP\x01Z3github.com/tarotfriend/platform/gen/go/dal/v1;dalv1\xa2\x02\x03\x44XX\xaa\x02\x06\x44\x61l.V1\xca\x02\x06\x44\x61l\\V1\xe2\x02\x12\x44\x61l\\V1\\GPBMetadata\xea\x02\x07\x44\x61l::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dal.v1.shop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\ncom.dal.v1B\tShopProtoP\001Z3github.com/tarotfriend/platform/gen/go/dal/v1;dalv1\242\002\003DXX\252\002\006Dal.V1\312\002\006Dal\\V1\342\002\022Dal\\V1\\GPBMetadata\352\002\007Dal::V1'
  _globals['_SHOPIFYCUSTOMERMAP']._serialized_start=63
  _globals['_SHOPIFYCUSTOMERMAP']._serialized_end=333
  _globals['_WEBHOOKEVENTLOG']._serialized_start=336
  _globals['_WEBHOOKEVENTLOG']._serialized_end=666
# @@protoc_insertion_point(module_scope)
