// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dal/v1/caring.proto

package dalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaringPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`           // "weekly_check" | "mood_followup" | "milestone"
	Frequency     string                 `protobuf:"bytes,4,opt,name=frequency,proto3" json:"frequency,omitempty"` // "daily" | "weekly" | "monthly" | "one_time"
	Channel       string                 `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`     // "email" | "line" | "sms" | "phone"
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`       // "active" | "paused" | "completed" | "cancelled"
	NextTriggerAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=next_trigger_at,json=nextTriggerAt,proto3" json:"next_trigger_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaringPlan) Reset() {
	*x = CaringPlan{}
	mi := &file_dal_v1_caring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaringPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaringPlan) ProtoMessage() {}

func (x *CaringPlan) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_caring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaringPlan.ProtoReflect.Descriptor instead.
func (*CaringPlan) Descriptor() ([]byte, []int) {
	return file_dal_v1_caring_proto_rawDescGZIP(), []int{0}
}

func (x *CaringPlan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CaringPlan) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CaringPlan) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CaringPlan) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *CaringPlan) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CaringPlan) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CaringPlan) GetNextTriggerAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextTriggerAt
	}
	return nil
}

func (x *CaringPlan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CaringAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"` // "email" | "line" | "sms"
	TemplateId    string                 `protobuf:"bytes,5,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "sent" | "delivered" | "read" | "failed"
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaringAction) Reset() {
	*x = CaringAction{}
	mi := &file_dal_v1_caring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaringAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaringAction) ProtoMessage() {}

func (x *CaringAction) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_caring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaringAction.ProtoReflect.Descriptor instead.
func (*CaringAction) Descriptor() ([]byte, []int) {
	return file_dal_v1_caring_proto_rawDescGZIP(), []int{1}
}

func (x *CaringAction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CaringAction) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CaringAction) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CaringAction) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CaringAction) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CaringAction) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CaringAction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CaringAction) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type SentimentRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // "tarot_reading" | "feedback" | "chat"
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"` // -1.0 to 1.0
	Label         string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`   // "positive" | "neutral" | "negative" | "crisis"
	SourceRefId   string                 `protobuf:"bytes,6,opt,name=source_ref_id,json=sourceRefId,proto3" json:"source_ref_id,omitempty"`
	RecordedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentimentRecord) Reset() {
	*x = SentimentRecord{}
	mi := &file_dal_v1_caring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentimentRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentimentRecord) ProtoMessage() {}

func (x *SentimentRecord) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_caring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentimentRecord.ProtoReflect.Descriptor instead.
func (*SentimentRecord) Descriptor() ([]byte, []int) {
	return file_dal_v1_caring_proto_rawDescGZIP(), []int{2}
}

func (x *SentimentRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SentimentRecord) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SentimentRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SentimentRecord) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SentimentRecord) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SentimentRecord) GetSourceRefId() string {
	if x != nil {
		return x.SourceRefId
	}
	return ""
}

func (x *SentimentRecord) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

type CaringRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ConditionJson string                 `protobuf:"bytes,3,opt,name=condition_json,json=conditionJson,proto3" json:"condition_json,omitempty"` // JSON: {"type":"inactivity","days":7}
	ActionJson    string                 `protobuf:"bytes,4,opt,name=action_json,json=actionJson,proto3" json:"action_json,omitempty"`          // JSON: {"channel":"line","template":"comeback"}
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaringRule) Reset() {
	*x = CaringRule{}
	mi := &file_dal_v1_caring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaringRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaringRule) ProtoMessage() {}

func (x *CaringRule) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_caring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaringRule.ProtoReflect.Descriptor instead.
func (*CaringRule) Descriptor() ([]byte, []int) {
	return file_dal_v1_caring_proto_rawDescGZIP(), []int{3}
}

func (x *CaringRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CaringRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CaringRule) GetConditionJson() string {
	if x != nil {
		return x.ConditionJson
	}
	return ""
}

func (x *CaringRule) GetActionJson() string {
	if x != nil {
		return x.ActionJson
	}
	return ""
}

func (x *CaringRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CaringRule) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CaringRule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CaringTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"` // "email" | "line" | "sms"
	Locale        string                 `protobuf:"bytes,4,opt,name=locale,proto3" json:"locale,omitempty"`   // "zh-TW" | "en"
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Variables     []string               `protobuf:"bytes,7,rep,name=variables,proto3" json:"variables,omitempty"` // ["customer_name", "last_reading_date"]
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaringTemplate) Reset() {
	*x = CaringTemplate{}
	mi := &file_dal_v1_caring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaringTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaringTemplate) ProtoMessage() {}

func (x *CaringTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_caring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaringTemplate.ProtoReflect.Descriptor instead.
func (*CaringTemplate) Descriptor() ([]byte, []int) {
	return file_dal_v1_caring_proto_rawDescGZIP(), []int{4}
}

func (x *CaringTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CaringTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CaringTemplate) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CaringTemplate) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *CaringTemplate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CaringTemplate) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CaringTemplate) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *CaringTemplate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_dal_v1_caring_proto protoreflect.FileDescriptor

const file_dal_v1_caring_proto_rawDesc = "" +
	"\n" +
	"\x13dal/v1/caring.proto\x12\x06dal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x02\n" +
	"\n" +
	"CaringPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\tfrequency\x18\x04 \x01(\tR\tfrequency\x12\x18\n" +
	"\achannel\x18\x05 \x01(\tR\achannel\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12B\n" +
	"\x0fnext_trigger_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rnextTriggerAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xfa\x01\n" +
	"\fCaringAction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x1f\n" +
	"\vtemplate_id\x18\x05 \x01(\tR\n" +
	"templateId\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x123\n" +
	"\asent_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\xe7\x01\n" +
	"\x0fSentimentRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\x12\"\n" +
	"\rsource_ref_id\x18\x06 \x01(\tR\vsourceRefId\x12;\n" +
	"\vrecorded_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt\"\xec\x01\n" +
	"\n" +
	"CaringRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0econdition_json\x18\x03 \x01(\tR\rconditionJson\x12\x1f\n" +
	"\vaction_json\x18\x04 \x01(\tR\n" +
	"actionJson\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xed\x01\n" +
	"\x0eCaringTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x16\n" +
	"\x06locale\x18\x04 \x01(\tR\x06locale\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12\x1c\n" +
	"\tvariables\x18\a \x03(\tR\tvariables\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x87\x01\n" +
	"\n" +
	"com.dal.v1B\vCaringProtoP\x01Z3github.com/tarotfriend/platform/gen/go/dal/v1;dalv1\xa2\x02\x03DXX\xaa\x02\x06Dal.V1\xca\x02\x06Dal\\V1\xe2\x02\x12Dal\\V1\\GPBMetadata\xea\x02\aDal::V1b\x06proto3"

var (
	file_dal_v1_caring_proto_rawDescOnce sync.Once
	file_dal_v1_caring_proto_rawDescData []byte
)

func file_dal_v1_caring_proto_rawDescGZIP() []byte {
	file_dal_v1_caring_proto_rawDescOnce.Do(func() {
		file_dal_v1_caring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dal_v1_caring_proto_rawDesc), len(file_dal_v1_caring_proto_rawDesc)))
	})
	return file_dal_v1_caring_proto_rawDescData
}

var file_dal_v1_caring_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dal_v1_caring_proto_goTypes = []any{
	(*CaringPlan)(nil),            // 0: dal.v1.CaringPlan
	(*CaringAction)(nil),          // 1: dal.v1.CaringAction
	(*SentimentRecord)(nil),       // 2: dal.v1.SentimentRecord
	(*CaringRule)(nil),            // 3: dal.v1.CaringRule
	(*CaringTemplate)(nil),        // 4: dal.v1.CaringTemplate
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_dal_v1_caring_proto_depIdxs = []int32{
	5, // 0: dal.v1.CaringPlan.next_trigger_at:type_name -> google.protobuf.Timestamp
	5, // 1: dal.v1.CaringPlan.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: dal.v1.CaringAction.sent_at:type_name -> google.protobuf.Timestamp
	5, // 3: dal.v1.SentimentRecord.recorded_at:type_name -> google.protobuf.Timestamp
	5, // 4: dal.v1.CaringRule.created_at:type_name -> google.protobuf.Timestamp
	5, // 5: dal.v1.CaringTemplate.created_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_dal_v1_caring_proto_init() }
func file_dal_v1_caring_proto_init() {
	if File_dal_v1_caring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dal_v1_caring_proto_rawDesc), len(file_dal_v1_caring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dal_v1_caring_proto_goTypes,
		DependencyIndexes: file_dal_v1_caring_proto_depIdxs,
		MessageInfos:      file_dal_v1_caring_proto_msgTypes,
	}.Build()
	File_dal_v1_caring_proto = out.File
	file_dal_v1_caring_proto_goTypes = nil
	file_dal_v1_caring_proto_depIdxs = nil
}
