// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dal/v1/customer.proto

package dalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Customer struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email       string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Phone       string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Locale      string                 `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"` // "zh-TW" | "en"
	Tier        string                 `protobuf:"bytes,6,opt,name=tier,proto3" json:"tier,omitempty"`     // "free" | "premium" | "vip"
	Status      string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "active" | "suspended" | "deleted"
	// Birth chart data
	BirthData *BirthData `protobuf:"bytes,10,opt,name=birth_data,json=birthData,proto3" json:"birth_data,omitempty"`
	// Metadata
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_dal_v1_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_dal_v1_customer_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Customer) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Customer) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Customer) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *Customer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Customer) GetBirthData() *BirthData {
	if x != nil {
		return x.BirthData
	}
	return nil
}

func (x *Customer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Customer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BirthData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BirthDate     string                 `protobuf:"bytes,1,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"` // "1995-06-15"
	BirthTime     string                 `protobuf:"bytes,2,opt,name=birth_time,json=birthTime,proto3" json:"birth_time,omitempty"` // "14:30" or empty if unknown
	BirthCity     string                 `protobuf:"bytes,3,opt,name=birth_city,json=birthCity,proto3" json:"birth_city,omitempty"`
	BirthLat      float64                `protobuf:"fixed64,4,opt,name=birth_lat,json=birthLat,proto3" json:"birth_lat,omitempty"`
	BirthLng      float64                `protobuf:"fixed64,5,opt,name=birth_lng,json=birthLng,proto3" json:"birth_lng,omitempty"`
	ZodiacSign    string                 `protobuf:"bytes,6,opt,name=zodiac_sign,json=zodiacSign,proto3" json:"zodiac_sign,omitempty"`          // "gemini"
	ChineseZodiac string                 `protobuf:"bytes,7,opt,name=chinese_zodiac,json=chineseZodiac,proto3" json:"chinese_zodiac,omitempty"` // "pig"
	FiveElement   string                 `protobuf:"bytes,8,opt,name=five_element,json=fiveElement,proto3" json:"five_element,omitempty"`       // "fire"
	Occupation    string                 `protobuf:"bytes,9,opt,name=occupation,proto3" json:"occupation,omitempty"`
	Industry      string                 `protobuf:"bytes,10,opt,name=industry,proto3" json:"industry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BirthData) Reset() {
	*x = BirthData{}
	mi := &file_dal_v1_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BirthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirthData) ProtoMessage() {}

func (x *BirthData) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirthData.ProtoReflect.Descriptor instead.
func (*BirthData) Descriptor() ([]byte, []int) {
	return file_dal_v1_customer_proto_rawDescGZIP(), []int{1}
}

func (x *BirthData) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *BirthData) GetBirthTime() string {
	if x != nil {
		return x.BirthTime
	}
	return ""
}

func (x *BirthData) GetBirthCity() string {
	if x != nil {
		return x.BirthCity
	}
	return ""
}

func (x *BirthData) GetBirthLat() float64 {
	if x != nil {
		return x.BirthLat
	}
	return 0
}

func (x *BirthData) GetBirthLng() float64 {
	if x != nil {
		return x.BirthLng
	}
	return 0
}

func (x *BirthData) GetZodiacSign() string {
	if x != nil {
		return x.ZodiacSign
	}
	return ""
}

func (x *BirthData) GetChineseZodiac() string {
	if x != nil {
		return x.ChineseZodiac
	}
	return ""
}

func (x *BirthData) GetFiveElement() string {
	if x != nil {
		return x.FiveElement
	}
	return ""
}

func (x *BirthData) GetOccupation() string {
	if x != nil {
		return x.Occupation
	}
	return ""
}

func (x *BirthData) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

type CustomerContact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Relationship  string                 `protobuf:"bytes,4,opt,name=relationship,proto3" json:"relationship,omitempty"` // "spouse" | "child" | "parent" | "friend" | "partner"
	BirthData     *BirthData             `protobuf:"bytes,5,opt,name=birth_data,json=birthData,proto3" json:"birth_data,omitempty"`
	Notes         string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerContact) Reset() {
	*x = CustomerContact{}
	mi := &file_dal_v1_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerContact) ProtoMessage() {}

func (x *CustomerContact) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerContact.ProtoReflect.Descriptor instead.
func (*CustomerContact) Descriptor() ([]byte, []int) {
	return file_dal_v1_customer_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerContact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomerContact) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CustomerContact) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CustomerContact) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *CustomerContact) GetBirthData() *BirthData {
	if x != nil {
		return x.BirthData
	}
	return nil
}

func (x *CustomerContact) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CustomerContact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type FinanceRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                  // "purchase" | "refund" | "top_up" | "subscription"
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`                              // Decimal as string for precision
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`                          // "TWD" | "USD"
	ReferenceId   string                 `protobuf:"bytes,6,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"` // Order ID or subscription ID
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // "pending" | "completed" | "failed" | "reversed"
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinanceRecord) Reset() {
	*x = FinanceRecord{}
	mi := &file_dal_v1_customer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinanceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinanceRecord) ProtoMessage() {}

func (x *FinanceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_customer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinanceRecord.ProtoReflect.Descriptor instead.
func (*FinanceRecord) Descriptor() ([]byte, []int) {
	return file_dal_v1_customer_proto_rawDescGZIP(), []int{3}
}

func (x *FinanceRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FinanceRecord) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *FinanceRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FinanceRecord) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *FinanceRecord) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FinanceRecord) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *FinanceRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FinanceRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FinanceRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"` // "interest" | "behavior" | "demographic" | "custom"
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_dal_v1_customer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_customer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_dal_v1_customer_proto_rawDescGZIP(), []int{4}
}

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Tag) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type CustomerNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"` // "general" | "support" | "reading" | "care"
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerNote) Reset() {
	*x = CustomerNote{}
	mi := &file_dal_v1_customer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerNote) ProtoMessage() {}

func (x *CustomerNote) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_customer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerNote.ProtoReflect.Descriptor instead.
func (*CustomerNote) Descriptor() ([]byte, []int) {
	return file_dal_v1_customer_proto_rawDescGZIP(), []int{5}
}

func (x *CustomerNote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomerNote) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CustomerNote) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CustomerNote) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CustomerNote) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CustomerNote) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_dal_v1_customer_proto protoreflect.FileDescriptor

const file_dal_v1_customer_proto_rawDesc = "" +
	"\n" +
	"\x15dal/v1/customer.proto\x12\x06dal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x02\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06locale\x18\x05 \x01(\tR\x06locale\x12\x12\n" +
	"\x04tier\x18\x06 \x01(\tR\x04tier\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x120\n" +
	"\n" +
	"birth_data\x18\n" +
	" \x01(\v2\x11.dal.v1.BirthDataR\tbirthData\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc9\x02\n" +
	"\tBirthData\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x01 \x01(\tR\tbirthDate\x12\x1d\n" +
	"\n" +
	"birth_time\x18\x02 \x01(\tR\tbirthTime\x12\x1d\n" +
	"\n" +
	"birth_city\x18\x03 \x01(\tR\tbirthCity\x12\x1b\n" +
	"\tbirth_lat\x18\x04 \x01(\x01R\bbirthLat\x12\x1b\n" +
	"\tbirth_lng\x18\x05 \x01(\x01R\bbirthLng\x12\x1f\n" +
	"\vzodiac_sign\x18\x06 \x01(\tR\n" +
	"zodiacSign\x12%\n" +
	"\x0echinese_zodiac\x18\a \x01(\tR\rchineseZodiac\x12!\n" +
	"\ffive_element\x18\b \x01(\tR\vfiveElement\x12\x1e\n" +
	"\n" +
	"occupation\x18\t \x01(\tR\n" +
	"occupation\x12\x1a\n" +
	"\bindustry\x18\n" +
	" \x01(\tR\bindustry\"\x85\x02\n" +
	"\x0fCustomerContact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\"\n" +
	"\frelationship\x18\x04 \x01(\tR\frelationship\x120\n" +
	"\n" +
	"birth_data\x18\x05 \x01(\v2\x11.dal.v1.BirthDataR\tbirthData\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa0\x02\n" +
	"\rFinanceRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12!\n" +
	"\freference_id\x18\x06 \x01(\tR\vreferenceId\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"[\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\"\xcd\x01\n" +
	"\fCustomerNote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x89\x01\n" +
	"\n" +
	"com.dal.v1B\rCustomerProtoP\x01Z3github.com/tarotfriend/platform/gen/go/dal/v1;dalv1\xa2\x02\x03DXX\xaa\x02\x06Dal.V1\xca\x02\x06Dal\\V1\xe2\x02\x12Dal\\V1\\GPBMetadata\xea\x02\aDal::V1b\x06proto3"

var (
	file_dal_v1_customer_proto_rawDescOnce sync.Once
	file_dal_v1_customer_proto_rawDescData []byte
)

func file_dal_v1_customer_proto_rawDescGZIP() []byte {
	file_dal_v1_customer_proto_rawDescOnce.Do(func() {
		file_dal_v1_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dal_v1_customer_proto_rawDesc), len(file_dal_v1_customer_proto_rawDesc)))
	})
	return file_dal_v1_customer_proto_rawDescData
}

var file_dal_v1_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dal_v1_customer_proto_goTypes = []any{
	(*Customer)(nil),              // 0: dal.v1.Customer
	(*BirthData)(nil),             // 1: dal.v1.BirthData
	(*CustomerContact)(nil),       // 2: dal.v1.CustomerContact
	(*FinanceRecord)(nil),         // 3: dal.v1.FinanceRecord
	(*Tag)(nil),                   // 4: dal.v1.Tag
	(*CustomerNote)(nil),          // 5: dal.v1.CustomerNote
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_dal_v1_customer_proto_depIdxs = []int32{
	1, // 0: dal.v1.Customer.birth_data:type_name -> dal.v1.BirthData
	6, // 1: dal.v1.Customer.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: dal.v1.Customer.updated_at:type_name -> google.protobuf.Timestamp
	1, // 3: dal.v1.CustomerContact.birth_data:type_name -> dal.v1.BirthData
	6, // 4: dal.v1.CustomerContact.created_at:type_name -> google.protobuf.Timestamp
	6, // 5: dal.v1.FinanceRecord.created_at:type_name -> google.protobuf.Timestamp
	6, // 6: dal.v1.CustomerNote.created_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_dal_v1_customer_proto_init() }
func file_dal_v1_customer_proto_init() {
	if File_dal_v1_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dal_v1_customer_proto_rawDesc), len(file_dal_v1_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dal_v1_customer_proto_goTypes,
		DependencyIndexes: file_dal_v1_customer_proto_depIdxs,
		MessageInfos:      file_dal_v1_customer_proto_msgTypes,
	}.Build()
	File_dal_v1_customer_proto = out.File
	file_dal_v1_customer_proto_goTypes = nil
	file_dal_v1_customer_proto_depIdxs = nil
}
