// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dal/v1/dal.proto

package dalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CachePolicy int32

const (
	CachePolicy_CACHE_POLICY_UNSPECIFIED CachePolicy = 0
	CachePolicy_CACHE_POLICY_CACHE_FIRST CachePolicy = 1 // Check cache first, fallback to DB on miss
	CachePolicy_CACHE_POLICY_DB_FIRST    CachePolicy = 2 // Query DB directly, update cache
	CachePolicy_CACHE_POLICY_CACHE_ONLY  CachePolicy = 3 // Only query cache
	CachePolicy_CACHE_POLICY_NO_CACHE    CachePolicy = 4 // Bypass cache entirely
)

// Enum value maps for CachePolicy.
var (
	CachePolicy_name = map[int32]string{
		0: "CACHE_POLICY_UNSPECIFIED",
		1: "CACHE_POLICY_CACHE_FIRST",
		2: "CACHE_POLICY_DB_FIRST",
		3: "CACHE_POLICY_CACHE_ONLY",
		4: "CACHE_POLICY_NO_CACHE",
	}
	CachePolicy_value = map[string]int32{
		"CACHE_POLICY_UNSPECIFIED": 0,
		"CACHE_POLICY_CACHE_FIRST": 1,
		"CACHE_POLICY_DB_FIRST":    2,
		"CACHE_POLICY_CACHE_ONLY":  3,
		"CACHE_POLICY_NO_CACHE":    4,
	}
)

func (x CachePolicy) Enum() *CachePolicy {
	p := new(CachePolicy)
	*p = x
	return p
}

func (x CachePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CachePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_dal_v1_dal_proto_enumTypes[0].Descriptor()
}

func (CachePolicy) Type() protoreflect.EnumType {
	return &file_dal_v1_dal_proto_enumTypes[0]
}

func (x CachePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CachePolicy.Descriptor instead.
func (CachePolicy) EnumDescriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{0}
}

type WriteStrategy int32

const (
	WriteStrategy_WRITE_STRATEGY_UNSPECIFIED   WriteStrategy = 0
	WriteStrategy_WRITE_STRATEGY_WRITE_THROUGH WriteStrategy = 1 // Sync write to both DB + cache
	WriteStrategy_WRITE_STRATEGY_WRITE_BEHIND  WriteStrategy = 2 // Write cache first, async flush to DB
	WriteStrategy_WRITE_STRATEGY_WRITE_AROUND  WriteStrategy = 3 // Write DB only, skip cache
)

// Enum value maps for WriteStrategy.
var (
	WriteStrategy_name = map[int32]string{
		0: "WRITE_STRATEGY_UNSPECIFIED",
		1: "WRITE_STRATEGY_WRITE_THROUGH",
		2: "WRITE_STRATEGY_WRITE_BEHIND",
		3: "WRITE_STRATEGY_WRITE_AROUND",
	}
	WriteStrategy_value = map[string]int32{
		"WRITE_STRATEGY_UNSPECIFIED":   0,
		"WRITE_STRATEGY_WRITE_THROUGH": 1,
		"WRITE_STRATEGY_WRITE_BEHIND":  2,
		"WRITE_STRATEGY_WRITE_AROUND":  3,
	}
)

func (x WriteStrategy) Enum() *WriteStrategy {
	p := new(WriteStrategy)
	*p = x
	return p
}

func (x WriteStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_dal_v1_dal_proto_enumTypes[1].Descriptor()
}

func (WriteStrategy) Type() protoreflect.EnumType {
	return &file_dal_v1_dal_proto_enumTypes[1]
}

func (x WriteStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteStrategy.Descriptor instead.
func (WriteStrategy) EnumDescriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{1}
}

type CheckResponse_ServingStatus int32

const (
	CheckResponse_SERVING_STATUS_UNSPECIFIED CheckResponse_ServingStatus = 0
	CheckResponse_SERVING_STATUS_SERVING     CheckResponse_ServingStatus = 1
	CheckResponse_SERVING_STATUS_NOT_SERVING CheckResponse_ServingStatus = 2
)

// Enum value maps for CheckResponse_ServingStatus.
var (
	CheckResponse_ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNSPECIFIED",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_NOT_SERVING",
	}
	CheckResponse_ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNSPECIFIED": 0,
		"SERVING_STATUS_SERVING":     1,
		"SERVING_STATUS_NOT_SERVING": 2,
	}
)

func (x CheckResponse_ServingStatus) Enum() *CheckResponse_ServingStatus {
	p := new(CheckResponse_ServingStatus)
	*p = x
	return p
}

func (x CheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_dal_v1_dal_proto_enumTypes[2].Descriptor()
}

func (CheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_dal_v1_dal_proto_enumTypes[2]
}

func (x CheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckResponse_ServingStatus.Descriptor instead.
func (CheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{11, 0}
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`                                                                           // "customer" | "tarot" | "caring" | "shop" | "scheduler"
	Entity        string                 `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`                                                                             // "customer" | "appointment" | "order" ...
	Filters       map[string]string      `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value filter pairs
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy       string                 `protobuf:"bytes,6,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	CachePolicy   CachePolicy            `protobuf:"varint,7,opt,name=cache_policy,json=cachePolicy,proto3,enum=dal.v1.CachePolicy" json:"cache_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_dal_v1_dal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_dal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *QueryRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *QueryRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *QueryRequest) GetCachePolicy() CachePolicy {
	if x != nil {
		return x.CachePolicy
	}
	return CachePolicy_CACHE_POLICY_UNSPECIFIED
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       [][]byte               `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"` // JSON-encoded entity records
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	FromCache     bool                   `protobuf:"varint,3,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_dal_v1_dal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_dal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetRecords() [][]byte {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *QueryResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Entity        string                 `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"` // "create" | "update" | "delete"
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`     // JSON-encoded entity data
	Strategy      WriteStrategy          `protobuf:"varint,5,opt,name=strategy,proto3,enum=dal.v1.WriteStrategy" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_dal_v1_dal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_dal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{2}
}

func (x *WriteRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *WriteRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *WriteRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *WriteRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WriteRequest) GetStrategy() WriteStrategy {
	if x != nil {
		return x.Strategy
	}
	return WriteStrategy_WRITE_STRATEGY_UNSPECIFIED
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_dal_v1_dal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_dal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{3}
}

func (x *WriteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Entity        string                 `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Strategy      WriteStrategy          `protobuf:"varint,5,opt,name=strategy,proto3,enum=dal.v1.WriteStrategy" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchWriteRequest) Reset() {
	*x = BatchWriteRequest{}
	mi := &file_dal_v1_dal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchWriteRequest) ProtoMessage() {}

func (x *BatchWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_dal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchWriteRequest.ProtoReflect.Descriptor instead.
func (*BatchWriteRequest) Descriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{4}
}

func (x *BatchWriteRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *BatchWriteRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *BatchWriteRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *BatchWriteRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BatchWriteRequest) GetStrategy() WriteStrategy {
	if x != nil {
		return x.Strategy
	}
	return WriteStrategy_WRITE_STRATEGY_UNSPECIFIED
}

type BatchWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchWriteResponse) Reset() {
	*x = BatchWriteResponse{}
	mi := &file_dal_v1_dal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchWriteResponse) ProtoMessage() {}

func (x *BatchWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_dal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchWriteResponse.ProtoReflect.Descriptor instead.
func (*BatchWriteResponse) Descriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{5}
}

func (x *BatchWriteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BatchWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchWriteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // "customer" | "tarot" | "shop" ...
	Entity        string                 `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`   // "customer" | "order" | "appointment" ...
	Filters       map[string]string      `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_dal_v1_dal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_dal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SubscribeRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *SubscribeRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Entity        string                 `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"` // "INSERT" | "UPDATE" | "DELETE"
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`     // JSON-encoded entity data
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_dal_v1_dal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_dal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SubscribeResponse) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *SubscribeResponse) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *SubscribeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubscribeResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SubscribeResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IngestStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Entity        string                 `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Strategy      WriteStrategy          `protobuf:"varint,5,opt,name=strategy,proto3,enum=dal.v1.WriteStrategy" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestStreamRequest) Reset() {
	*x = IngestStreamRequest{}
	mi := &file_dal_v1_dal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestStreamRequest) ProtoMessage() {}

func (x *IngestStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_dal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestStreamRequest.ProtoReflect.Descriptor instead.
func (*IngestStreamRequest) Descriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{8}
}

func (x *IngestStreamRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *IngestStreamRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *IngestStreamRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *IngestStreamRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IngestStreamRequest) GetStrategy() WriteStrategy {
	if x != nil {
		return x.Strategy
	}
	return WriteStrategy_WRITE_STRATEGY_UNSPECIFIED
}

type IngestStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestStreamResponse) Reset() {
	*x = IngestStreamResponse{}
	mi := &file_dal_v1_dal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestStreamResponse) ProtoMessage() {}

func (x *IngestStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_dal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestStreamResponse.ProtoReflect.Descriptor instead.
func (*IngestStreamResponse) Descriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{9}
}

func (x *IngestStreamResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IngestStreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestStreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // Optional: check specific storage engine
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_dal_v1_dal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_dal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{10}
}

func (x *CheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        CheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=dal.v1.CheckResponse_ServingStatus" json:"status,omitempty"`
	Details       map[string]string           `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Per-engine health info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_dal_v1_dal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_dal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_dal_v1_dal_proto_rawDescGZIP(), []int{11}
}

func (x *CheckResponse) GetStatus() CheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return CheckResponse_SERVING_STATUS_UNSPECIFIED
}

func (x *CheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_dal_v1_dal_proto protoreflect.FileDescriptor

const file_dal_v1_dal_proto_rawDesc = "" +
	"\n" +
	"\x10dal/v1/dal.proto\x12\x06dal.v1\"\xba\x02\n" +
	"\fQueryRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\tR\x06entity\x12;\n" +
	"\afilters\x18\x03 \x03(\v2!.dal.v1.QueryRequest.FiltersEntryR\afilters\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12\x19\n" +
	"\border_by\x18\x06 \x01(\tR\aorderBy\x126\n" +
	"\fcache_policy\x18\a \x01(\x0e2\x13.dal.v1.CachePolicyR\vcachePolicy\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\rQueryResponse\x12\x18\n" +
	"\arecords\x18\x01 \x03(\fR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x03 \x01(\bR\tfromCache\"\xab\x01\n" +
	"\fWriteRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\tR\x06entity\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x121\n" +
	"\bstrategy\x18\x05 \x01(\x0e2\x15.dal.v1.WriteStrategyR\bstrategy\"O\n" +
	"\rWriteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xb0\x01\n" +
	"\x11BatchWriteRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\tR\x06entity\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x121\n" +
	"\bstrategy\x18\x05 \x01(\x0e2\x15.dal.v1.WriteStrategyR\bstrategy\"T\n" +
	"\x12BatchWriteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xc1\x01\n" +
	"\x10SubscribeRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\tR\x06entity\x12?\n" +
	"\afilters\x18\x03 \x03(\v2%.dal.v1.SubscribeRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x02\n" +
	"\x11SubscribeResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\tR\x06entity\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12C\n" +
	"\bmetadata\x18\x06 \x03(\v2'.dal.v1.SubscribeResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	"\x13IngestStreamRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\tR\x06entity\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x121\n" +
	"\bstrategy\x18\x05 \x01(\x0e2\x15.dal.v1.WriteStrategyR\bstrategy\"V\n" +
	"\x14IngestStreamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"(\n" +
	"\fCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xb3\x02\n" +
	"\rCheckResponse\x12;\n" +
	"\x06status\x18\x01 \x01(\x0e2#.dal.v1.CheckResponse.ServingStatusR\x06status\x12<\n" +
	"\adetails\x18\x02 \x03(\v2\".dal.v1.CheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\rServingStatus\x12\x1e\n" +
	"\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVING_STATUS_SERVING\x10\x01\x12\x1e\n" +
	"\x1aSERVING_STATUS_NOT_SERVING\x10\x02*\x9c\x01\n" +
	"\vCachePolicy\x12\x1c\n" +
	"\x18CACHE_POLICY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CACHE_POLICY_CACHE_FIRST\x10\x01\x12\x19\n" +
	"\x15CACHE_POLICY_DB_FIRST\x10\x02\x12\x1b\n" +
	"\x17CACHE_POLICY_CACHE_ONLY\x10\x03\x12\x19\n" +
	"\x15CACHE_POLICY_NO_CACHE\x10\x04*\x93\x01\n" +
	"\rWriteStrategy\x12\x1e\n" +
	"\x1aWRITE_STRATEGY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cWRITE_STRATEGY_WRITE_THROUGH\x10\x01\x12\x1f\n" +
	"\x1bWRITE_STRATEGY_WRITE_BEHIND\x10\x02\x12\x1f\n" +
	"\x1bWRITE_STRATEGY_WRITE_AROUND\x10\x032\x91\x03\n" +
	"\x11DataAccessService\x124\n" +
	"\x05Query\x12\x14.dal.v1.QueryRequest\x1a\x15.dal.v1.QueryResponse\x124\n" +
	"\x05Write\x12\x14.dal.v1.WriteRequest\x1a\x15.dal.v1.WriteResponse\x12G\n" +
	"\n" +
	"BatchWrite\x12\x19.dal.v1.BatchWriteRequest\x1a\x1a.dal.v1.BatchWriteResponse(\x010\x01\x12B\n" +
	"\tSubscribe\x12\x18.dal.v1.SubscribeRequest\x1a\x19.dal.v1.SubscribeResponse0\x01\x12M\n" +
	"\fIngestStream\x12\x1b.dal.v1.IngestStreamRequest\x1a\x1c.dal.v1.IngestStreamResponse(\x010\x01\x124\n" +
	"\x05Check\x12\x14.dal.v1.CheckRequest\x1a\x15.dal.v1.CheckResponseB\x84\x01\n" +
	"\n" +
	"com.dal.v1B\bDalProtoP\x01Z3github.com/tarotfriend/platform/gen/go/dal/v1;dalv1\xa2\x02\x03DXX\xaa\x02\x06Dal.V1\xca\x02\x06Dal\\V1\xe2\x02\x12Dal\\V1\\GPBMetadata\xea\x02\aDal::V1b\x06proto3"

var (
	file_dal_v1_dal_proto_rawDescOnce sync.Once
	file_dal_v1_dal_proto_rawDescData []byte
)

func file_dal_v1_dal_proto_rawDescGZIP() []byte {
	file_dal_v1_dal_proto_rawDescOnce.Do(func() {
		file_dal_v1_dal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dal_v1_dal_proto_rawDesc), len(file_dal_v1_dal_proto_rawDesc)))
	})
	return file_dal_v1_dal_proto_rawDescData
}

var file_dal_v1_dal_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_dal_v1_dal_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_dal_v1_dal_proto_goTypes = []any{
	(CachePolicy)(0),                 // 0: dal.v1.CachePolicy
	(WriteStrategy)(0),               // 1: dal.v1.WriteStrategy
	(CheckResponse_ServingStatus)(0), // 2: dal.v1.CheckResponse.ServingStatus
	(*QueryRequest)(nil),             // 3: dal.v1.QueryRequest
	(*QueryResponse)(nil),            // 4: dal.v1.QueryResponse
	(*WriteRequest)(nil),             // 5: dal.v1.WriteRequest
	(*WriteResponse)(nil),            // 6: dal.v1.WriteResponse
	(*BatchWriteRequest)(nil),        // 7: dal.v1.BatchWriteRequest
	(*BatchWriteResponse)(nil),       // 8: dal.v1.BatchWriteResponse
	(*SubscribeRequest)(nil),         // 9: dal.v1.SubscribeRequest
	(*SubscribeResponse)(nil),        // 10: dal.v1.SubscribeResponse
	(*IngestStreamRequest)(nil),      // 11: dal.v1.IngestStreamRequest
	(*IngestStreamResponse)(nil),     // 12: dal.v1.IngestStreamResponse
	(*CheckRequest)(nil),             // 13: dal.v1.CheckRequest
	(*CheckResponse)(nil),            // 14: dal.v1.CheckResponse
	nil,                              // 15: dal.v1.QueryRequest.FiltersEntry
	nil,                              // 16: dal.v1.SubscribeRequest.FiltersEntry
	nil,                              // 17: dal.v1.SubscribeResponse.MetadataEntry
	nil,                              // 18: dal.v1.CheckResponse.DetailsEntry
}
var file_dal_v1_dal_proto_depIdxs = []int32{
	15, // 0: dal.v1.QueryRequest.filters:type_name -> dal.v1.QueryRequest.FiltersEntry
	0,  // 1: dal.v1.QueryRequest.cache_policy:type_name -> dal.v1.CachePolicy
	1,  // 2: dal.v1.WriteRequest.strategy:type_name -> dal.v1.WriteStrategy
	1,  // 3: dal.v1.BatchWriteRequest.strategy:type_name -> dal.v1.WriteStrategy
	16, // 4: dal.v1.SubscribeRequest.filters:type_name -> dal.v1.SubscribeRequest.FiltersEntry
	17, // 5: dal.v1.SubscribeResponse.metadata:type_name -> dal.v1.SubscribeResponse.MetadataEntry
	1,  // 6: dal.v1.IngestStreamRequest.strategy:type_name -> dal.v1.WriteStrategy
	2,  // 7: dal.v1.CheckResponse.status:type_name -> dal.v1.CheckResponse.ServingStatus
	18, // 8: dal.v1.CheckResponse.details:type_name -> dal.v1.CheckResponse.DetailsEntry
	3,  // 9: dal.v1.DataAccessService.Query:input_type -> dal.v1.QueryRequest
	5,  // 10: dal.v1.DataAccessService.Write:input_type -> dal.v1.WriteRequest
	7,  // 11: dal.v1.DataAccessService.BatchWrite:input_type -> dal.v1.BatchWriteRequest
	9,  // 12: dal.v1.DataAccessService.Subscribe:input_type -> dal.v1.SubscribeRequest
	11, // 13: dal.v1.DataAccessService.IngestStream:input_type -> dal.v1.IngestStreamRequest
	13, // 14: dal.v1.DataAccessService.Check:input_type -> dal.v1.CheckRequest
	4,  // 15: dal.v1.DataAccessService.Query:output_type -> dal.v1.QueryResponse
	6,  // 16: dal.v1.DataAccessService.Write:output_type -> dal.v1.WriteResponse
	8,  // 17: dal.v1.DataAccessService.BatchWrite:output_type -> dal.v1.BatchWriteResponse
	10, // 18: dal.v1.DataAccessService.Subscribe:output_type -> dal.v1.SubscribeResponse
	12, // 19: dal.v1.DataAccessService.IngestStream:output_type -> dal.v1.IngestStreamResponse
	14, // 20: dal.v1.DataAccessService.Check:output_type -> dal.v1.CheckResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_dal_v1_dal_proto_init() }
func file_dal_v1_dal_proto_init() {
	if File_dal_v1_dal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dal_v1_dal_proto_rawDesc), len(file_dal_v1_dal_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dal_v1_dal_proto_goTypes,
		DependencyIndexes: file_dal_v1_dal_proto_depIdxs,
		EnumInfos:         file_dal_v1_dal_proto_enumTypes,
		MessageInfos:      file_dal_v1_dal_proto_msgTypes,
	}.Build()
	File_dal_v1_dal_proto = out.File
	file_dal_v1_dal_proto_goTypes = nil
	file_dal_v1_dal_proto_depIdxs = nil
}
