// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: dal/v1/dal.proto

package dalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataAccessService_Query_FullMethodName        = "/dal.v1.DataAccessService/Query"
	DataAccessService_Write_FullMethodName        = "/dal.v1.DataAccessService/Write"
	DataAccessService_BatchWrite_FullMethodName   = "/dal.v1.DataAccessService/BatchWrite"
	DataAccessService_Subscribe_FullMethodName    = "/dal.v1.DataAccessService/Subscribe"
	DataAccessService_IngestStream_FullMethodName = "/dal.v1.DataAccessService/IngestStream"
	DataAccessService_Check_FullMethodName        = "/dal.v1.DataAccessService/Check"
)

// DataAccessServiceClient is the client API for DataAccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataAccessServiceClient interface {
	// Synchronous CRUD
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	// Bidirectional streaming: batch writes with per-item responses
	BatchWrite(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchWriteRequest, BatchWriteResponse], error)
	// Server streaming: subscribe to entity change events
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error)
	// Bidirectional streaming: high-throughput data ingestion
	IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestStreamRequest, IngestStreamResponse], error)
	// Health check
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type dataAccessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataAccessServiceClient(cc grpc.ClientConnInterface) DataAccessServiceClient {
	return &dataAccessServiceClient{cc}
}

func (c *dataAccessServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, DataAccessService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataAccessServiceClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, DataAccessService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataAccessServiceClient) BatchWrite(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchWriteRequest, BatchWriteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataAccessService_ServiceDesc.Streams[0], DataAccessService_BatchWrite_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchWriteRequest, BatchWriteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataAccessService_BatchWriteClient = grpc.BidiStreamingClient[BatchWriteRequest, BatchWriteResponse]

func (c *dataAccessServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataAccessService_ServiceDesc.Streams[1], DataAccessService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataAccessService_SubscribeClient = grpc.ServerStreamingClient[SubscribeResponse]

func (c *dataAccessServiceClient) IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestStreamRequest, IngestStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataAccessService_ServiceDesc.Streams[2], DataAccessService_IngestStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestStreamRequest, IngestStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataAccessService_IngestStreamClient = grpc.BidiStreamingClient[IngestStreamRequest, IngestStreamResponse]

func (c *dataAccessServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, DataAccessService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataAccessServiceServer is the server API for DataAccessService service.
// All implementations must embed UnimplementedDataAccessServiceServer
// for forward compatibility.
type DataAccessServiceServer interface {
	// Synchronous CRUD
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	// Bidirectional streaming: batch writes with per-item responses
	BatchWrite(grpc.BidiStreamingServer[BatchWriteRequest, BatchWriteResponse]) error
	// Server streaming: subscribe to entity change events
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error
	// Bidirectional streaming: high-throughput data ingestion
	IngestStream(grpc.BidiStreamingServer[IngestStreamRequest, IngestStreamResponse]) error
	// Health check
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	mustEmbedUnimplementedDataAccessServiceServer()
}

// UnimplementedDataAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataAccessServiceServer struct{}

func (UnimplementedDataAccessServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedDataAccessServiceServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedDataAccessServiceServer) BatchWrite(grpc.BidiStreamingServer[BatchWriteRequest, BatchWriteResponse]) error {
	return status.Error(codes.Unimplemented, "method BatchWrite not implemented")
}
func (UnimplementedDataAccessServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedDataAccessServiceServer) IngestStream(grpc.BidiStreamingServer[IngestStreamRequest, IngestStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method IngestStream not implemented")
}
func (UnimplementedDataAccessServiceServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedDataAccessServiceServer) mustEmbedUnimplementedDataAccessServiceServer() {}
func (UnimplementedDataAccessServiceServer) testEmbeddedByValue()                           {}

// UnsafeDataAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataAccessServiceServer will
// result in compilation errors.
type UnsafeDataAccessServiceServer interface {
	mustEmbedUnimplementedDataAccessServiceServer()
}

func RegisterDataAccessServiceServer(s grpc.ServiceRegistrar, srv DataAccessServiceServer) {
	// If the following call panics, it indicates UnimplementedDataAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataAccessService_ServiceDesc, srv)
}

func _DataAccessService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAccessServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataAccessService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAccessServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataAccessService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAccessServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataAccessService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAccessServiceServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataAccessService_BatchWrite_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataAccessServiceServer).BatchWrite(&grpc.GenericServerStream[BatchWriteRequest, BatchWriteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataAccessService_BatchWriteServer = grpc.BidiStreamingServer[BatchWriteRequest, BatchWriteResponse]

func _DataAccessService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataAccessServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataAccessService_SubscribeServer = grpc.ServerStreamingServer[SubscribeResponse]

func _DataAccessService_IngestStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataAccessServiceServer).IngestStream(&grpc.GenericServerStream[IngestStreamRequest, IngestStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataAccessService_IngestStreamServer = grpc.BidiStreamingServer[IngestStreamRequest, IngestStreamResponse]

func _DataAccessService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAccessServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataAccessService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAccessServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataAccessService_ServiceDesc is the grpc.ServiceDesc for DataAccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataAccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dal.v1.DataAccessService",
	HandlerType: (*DataAccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _DataAccessService_Query_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _DataAccessService_Write_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _DataAccessService_Check_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BatchWrite",
			Handler:       _DataAccessService_BatchWrite_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _DataAccessService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "IngestStream",
			Handler:       _DataAccessService_IngestStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dal/v1/dal.proto",
}
