// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dal/v1/scheduler.proto

package dalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tarotist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Specialties   []string               `protobuf:"bytes,5,rep,name=specialties,proto3" json:"specialties,omitempty"` // ["love", "career", "spiritual"]
	Rating        float64                `protobuf:"fixed64,6,opt,name=rating,proto3" json:"rating,omitempty"`         // 0.0 - 5.0
	TotalReviews  int32                  `protobuf:"varint,7,opt,name=total_reviews,json=totalReviews,proto3" json:"total_reviews,omitempty"`
	HourlyRate    string                 `protobuf:"bytes,8,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"` // Decimal as string
	Currency      string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`                       // "TWD"
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`                          // "active" | "inactive" | "suspended"
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tarotist) Reset() {
	*x = Tarotist{}
	mi := &file_dal_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tarotist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tarotist) ProtoMessage() {}

func (x *Tarotist) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tarotist.ProtoReflect.Descriptor instead.
func (*Tarotist) Descriptor() ([]byte, []int) {
	return file_dal_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *Tarotist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tarotist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tarotist) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Tarotist) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Tarotist) GetSpecialties() []string {
	if x != nil {
		return x.Specialties
	}
	return nil
}

func (x *Tarotist) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Tarotist) GetTotalReviews() int32 {
	if x != nil {
		return x.TotalReviews
	}
	return 0
}

func (x *Tarotist) GetHourlyRate() string {
	if x != nil {
		return x.HourlyRate
	}
	return ""
}

func (x *Tarotist) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Tarotist) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tarotist) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Availability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TarotistId    string                 `protobuf:"bytes,2,opt,name=tarotist_id,json=tarotistId,proto3" json:"tarotist_id,omitempty"`
	DayOfWeek     int32                  `protobuf:"varint,3,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"` // 0=Sunday, 6=Saturday
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`    // "09:00"
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`          // "17:00"
	IsRecurring   bool                   `protobuf:"varint,6,opt,name=is_recurring,json=isRecurring,proto3" json:"is_recurring,omitempty"`
	SpecificDate  string                 `protobuf:"bytes,7,opt,name=specific_date,json=specificDate,proto3" json:"specific_date,omitempty"` // "2025-03-15" for one-off slots
	IsAvailable   bool                   `protobuf:"varint,8,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Availability) Reset() {
	*x = Availability{}
	mi := &file_dal_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Availability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Availability) ProtoMessage() {}

func (x *Availability) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Availability.ProtoReflect.Descriptor instead.
func (*Availability) Descriptor() ([]byte, []int) {
	return file_dal_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *Availability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Availability) GetTarotistId() string {
	if x != nil {
		return x.TarotistId
	}
	return ""
}

func (x *Availability) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *Availability) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Availability) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Availability) GetIsRecurring() bool {
	if x != nil {
		return x.IsRecurring
	}
	return false
}

func (x *Availability) GetSpecificDate() string {
	if x != nil {
		return x.SpecificDate
	}
	return ""
}

func (x *Availability) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type Appointment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	TarotistId    string                 `protobuf:"bytes,3,opt,name=tarotist_id,json=tarotistId,proto3" json:"tarotist_id,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`     // "online" | "in_person"
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "pending" | "confirmed" | "completed" | "cancelled" | "no_show"
	Topic         string                 `protobuf:"bytes,8,opt,name=topic,proto3" json:"topic,omitempty"`
	MeetingUrl    string                 `protobuf:"bytes,9,opt,name=meeting_url,json=meetingUrl,proto3" json:"meeting_url,omitempty"`
	Notes         string                 `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_dal_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_dal_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *Appointment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Appointment) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Appointment) GetTarotistId() string {
	if x != nil {
		return x.TarotistId
	}
	return ""
}

func (x *Appointment) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *Appointment) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *Appointment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Appointment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Appointment) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Appointment) GetMeetingUrl() string {
	if x != nil {
		return x.MeetingUrl
	}
	return ""
}

func (x *Appointment) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Appointment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppointmentId string                 `protobuf:"bytes,2,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	TarotistId    string                 `protobuf:"bytes,4,opt,name=tarotist_id,json=tarotistId,proto3" json:"tarotist_id,omitempty"`
	Rating        int32                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"` // 1-5
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_dal_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_dal_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

func (x *Review) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Review) GetTarotistId() string {
	if x != nil {
		return x.TarotistId
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_dal_v1_scheduler_proto protoreflect.FileDescriptor

const file_dal_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x16dal/v1/scheduler.proto\x12\x06dal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x02\n" +
	"\bTarotist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12 \n" +
	"\vspecialties\x18\x05 \x03(\tR\vspecialties\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x01R\x06rating\x12#\n" +
	"\rtotal_reviews\x18\a \x01(\x05R\ftotalReviews\x12\x1f\n" +
	"\vhourly_rate\x18\b \x01(\tR\n" +
	"hourlyRate\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x84\x02\n" +
	"\fAvailability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtarotist_id\x18\x02 \x01(\tR\n" +
	"tarotistId\x12\x1e\n" +
	"\vday_of_week\x18\x03 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12!\n" +
	"\fis_recurring\x18\x06 \x01(\bR\visRecurring\x12#\n" +
	"\rspecific_date\x18\a \x01(\tR\fspecificDate\x12!\n" +
	"\fis_available\x18\b \x01(\bR\visAvailable\"\xfd\x02\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vtarotist_id\x18\x03 \x01(\tR\n" +
	"tarotistId\x125\n" +
	"\bstart_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05topic\x18\b \x01(\tR\x05topic\x12\x1f\n" +
	"\vmeeting_url\x18\t \x01(\tR\n" +
	"meetingUrl\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xee\x01\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eappointment_id\x18\x02 \x01(\tR\rappointmentId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vtarotist_id\x18\x04 \x01(\tR\n" +
	"tarotistId\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x8a\x01\n" +
	"\n" +
	"com.dal.v1B\x0eSchedulerProtoP\x01Z3github.com/tarotfriend/platform/gen/go/dal/v1;dalv1\xa2\x02\x03DXX\xaa\x02\x06Dal.V1\xca\x02\x06Dal\\V1\xe2\x02\x12Dal\\V1\\GPBMetadata\xea\x02\aDal::V1b\x06proto3"

var (
	file_dal_v1_scheduler_proto_rawDescOnce sync.Once
	file_dal_v1_scheduler_proto_rawDescData []byte
)

func file_dal_v1_scheduler_proto_rawDescGZIP() []byte {
	file_dal_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_dal_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dal_v1_scheduler_proto_rawDesc), len(file_dal_v1_scheduler_proto_rawDesc)))
	})
	return file_dal_v1_scheduler_proto_rawDescData
}

var file_dal_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dal_v1_scheduler_proto_goTypes = []any{
	(*Tarotist)(nil),              // 0: dal.v1.Tarotist
	(*Availability)(nil),          // 1: dal.v1.Availability
	(*Appointment)(nil),           // 2: dal.v1.Appointment
	(*Review)(nil),                // 3: dal.v1.Review
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_dal_v1_scheduler_proto_depIdxs = []int32{
	4, // 0: dal.v1.Tarotist.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: dal.v1.Appointment.start_at:type_name -> google.protobuf.Timestamp
	4, // 2: dal.v1.Appointment.end_at:type_name -> google.protobuf.Timestamp
	4, // 3: dal.v1.Appointment.created_at:type_name -> google.protobuf.Timestamp
	4, // 4: dal.v1.Review.created_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_dal_v1_scheduler_proto_init() }
func file_dal_v1_scheduler_proto_init() {
	if File_dal_v1_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dal_v1_scheduler_proto_rawDesc), len(file_dal_v1_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dal_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_dal_v1_scheduler_proto_depIdxs,
		MessageInfos:      file_dal_v1_scheduler_proto_msgTypes,
	}.Build()
	File_dal_v1_scheduler_proto = out.File
	file_dal_v1_scheduler_proto_goTypes = nil
	file_dal_v1_scheduler_proto_depIdxs = nil
}
