// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dal/v1/shop.proto

package dalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShopifyCustomerMap struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId        string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`                        // Internal customer_db.customer.id
	ShopifyCustomerId string                 `protobuf:"bytes,3,opt,name=shopify_customer_id,json=shopifyCustomerId,proto3" json:"shopify_customer_id,omitempty"` // Shopify's customer ID
	ShopifyEmail      string                 `protobuf:"bytes,4,opt,name=shopify_email,json=shopifyEmail,proto3" json:"shopify_email,omitempty"`
	SyncedAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=synced_at,json=syncedAt,proto3" json:"synced_at,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ShopifyCustomerMap) Reset() {
	*x = ShopifyCustomerMap{}
	mi := &file_dal_v1_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopifyCustomerMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopifyCustomerMap) ProtoMessage() {}

func (x *ShopifyCustomerMap) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopifyCustomerMap.ProtoReflect.Descriptor instead.
func (*ShopifyCustomerMap) Descriptor() ([]byte, []int) {
	return file_dal_v1_shop_proto_rawDescGZIP(), []int{0}
}

func (x *ShopifyCustomerMap) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShopifyCustomerMap) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ShopifyCustomerMap) GetShopifyCustomerId() string {
	if x != nil {
		return x.ShopifyCustomerId
	}
	return ""
}

func (x *ShopifyCustomerMap) GetShopifyEmail() string {
	if x != nil {
		return x.ShopifyEmail
	}
	return ""
}

func (x *ShopifyCustomerMap) GetSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncedAt
	}
	return nil
}

func (x *ShopifyCustomerMap) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type WebhookEventLog struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopifyWebhookId  string                 `protobuf:"bytes,2,opt,name=shopify_webhook_id,json=shopifyWebhookId,proto3" json:"shopify_webhook_id,omitempty"` // Shopify's idempotency key
	Topic             string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`                                                 // "orders/create" | "orders/paid" | ...
	ShopifyResourceId string                 `protobuf:"bytes,4,opt,name=shopify_resource_id,json=shopifyResourceId,proto3" json:"shopify_resource_id,omitempty"`
	PayloadJson       string                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // Raw Shopify webhook JSON
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                              // "pending" | "processed" | "failed"
	ProcessedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WebhookEventLog) Reset() {
	*x = WebhookEventLog{}
	mi := &file_dal_v1_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEventLog) ProtoMessage() {}

func (x *WebhookEventLog) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEventLog.ProtoReflect.Descriptor instead.
func (*WebhookEventLog) Descriptor() ([]byte, []int) {
	return file_dal_v1_shop_proto_rawDescGZIP(), []int{1}
}

func (x *WebhookEventLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebhookEventLog) GetShopifyWebhookId() string {
	if x != nil {
		return x.ShopifyWebhookId
	}
	return ""
}

func (x *WebhookEventLog) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *WebhookEventLog) GetShopifyResourceId() string {
	if x != nil {
		return x.ShopifyResourceId
	}
	return ""
}

func (x *WebhookEventLog) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *WebhookEventLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WebhookEventLog) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *WebhookEventLog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_dal_v1_shop_proto protoreflect.FileDescriptor

const file_dal_v1_shop_proto_rawDesc = "" +
	"\n" +
	"\x11dal/v1/shop.proto\x12\x06dal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x02\n" +
	"\x12ShopifyCustomerMap\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12.\n" +
	"\x13shopify_customer_id\x18\x03 \x01(\tR\x11shopifyCustomerId\x12#\n" +
	"\rshopify_email\x18\x04 \x01(\tR\fshopifyEmail\x127\n" +
	"\tsynced_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bsyncedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xca\x02\n" +
	"\x0fWebhookEventLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12shopify_webhook_id\x18\x02 \x01(\tR\x10shopifyWebhookId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12.\n" +
	"\x13shopify_resource_id\x18\x04 \x01(\tR\x11shopifyResourceId\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\tR\vpayloadJson\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12=\n" +
	"\fprocessed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x85\x01\n" +
	"\n" +
	"com.dal.v1B\tShopProtoP\x01Z3github.com/tarotfriend/platform/gen/go/dal/v1;dalv1\xa2\x02\x03DXX\xaa\x02\x06Dal.V1\xca\x02\x06Dal\\V1\xe2\x02\x12Dal\\V1\\GPBMetadata\xea\x02\aDal::V1b\x06proto3"

var (
	file_dal_v1_shop_proto_rawDescOnce sync.Once
	file_dal_v1_shop_proto_rawDescData []byte
)

func file_dal_v1_shop_proto_rawDescGZIP() []byte {
	file_dal_v1_shop_proto_rawDescOnce.Do(func() {
		file_dal_v1_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dal_v1_shop_proto_rawDesc), len(file_dal_v1_shop_proto_rawDesc)))
	})
	return file_dal_v1_shop_proto_rawDescData
}

var file_dal_v1_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dal_v1_shop_proto_goTypes = []any{
	(*ShopifyCustomerMap)(nil),    // 0: dal.v1.ShopifyCustomerMap
	(*WebhookEventLog)(nil),       // 1: dal.v1.WebhookEventLog
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_dal_v1_shop_proto_depIdxs = []int32{
	2, // 0: dal.v1.ShopifyCustomerMap.synced_at:type_name -> google.protobuf.Timestamp
	2, // 1: dal.v1.ShopifyCustomerMap.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: dal.v1.WebhookEventLog.processed_at:type_name -> google.protobuf.Timestamp
	2, // 3: dal.v1.WebhookEventLog.created_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dal_v1_shop_proto_init() }
func file_dal_v1_shop_proto_init() {
	if File_dal_v1_shop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dal_v1_shop_proto_rawDesc), len(file_dal_v1_shop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dal_v1_shop_proto_goTypes,
		DependencyIndexes: file_dal_v1_shop_proto_depIdxs,
		MessageInfos:      file_dal_v1_shop_proto_msgTypes,
	}.Build()
	File_dal_v1_shop_proto = out.File
	file_dal_v1_shop_proto_goTypes = nil
	file_dal_v1_shop_proto_depIdxs = nil
}
