// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/v1/event.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// TarotReading events
	EventType_EVENT_TYPE_READING_COMPLETED EventType = 1
	EventType_EVENT_TYPE_READING_FEEDBACK  EventType = 2
	EventType_EVENT_TYPE_CRISIS_DETECTED   EventType = 3
	// Customer events
	EventType_EVENT_TYPE_CUSTOMER_CREATED      EventType = 10
	EventType_EVENT_TYPE_CUSTOMER_UPDATED      EventType = 11
	EventType_EVENT_TYPE_CUSTOMER_TIER_CHANGED EventType = 12
	// Shopping events
	EventType_EVENT_TYPE_ORDER_CREATED    EventType = 20
	EventType_EVENT_TYPE_ORDER_PAID       EventType = 21
	EventType_EVENT_TYPE_ORDER_FULFILLED  EventType = 22
	EventType_EVENT_TYPE_ORDER_CANCELLED  EventType = 23
	EventType_EVENT_TYPE_REFUND_CREATED   EventType = 24
	EventType_EVENT_TYPE_CHECKOUT_STARTED EventType = 25
	EventType_EVENT_TYPE_PRODUCT_UPDATED  EventType = 26
	// Caring events
	EventType_EVENT_TYPE_CARING_ACTION_SENT      EventType = 30
	EventType_EVENT_TYPE_CARING_ACTION_DELIVERED EventType = 31
	EventType_EVENT_TYPE_CARING_ACTION_READ      EventType = 32
	EventType_EVENT_TYPE_SENTIMENT_RECORDED      EventType = 33
	// Scheduler events
	EventType_EVENT_TYPE_APPOINTMENT_CREATED   EventType = 40
	EventType_EVENT_TYPE_APPOINTMENT_CONFIRMED EventType = 41
	EventType_EVENT_TYPE_APPOINTMENT_COMPLETED EventType = 42
	EventType_EVENT_TYPE_APPOINTMENT_CANCELLED EventType = 43
	EventType_EVENT_TYPE_REVIEW_SUBMITTED      EventType = 44
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_READING_COMPLETED",
		2:  "EVENT_TYPE_READING_FEEDBACK",
		3:  "EVENT_TYPE_CRISIS_DETECTED",
		10: "EVENT_TYPE_CUSTOMER_CREATED",
		11: "EVENT_TYPE_CUSTOMER_UPDATED",
		12: "EVENT_TYPE_CUSTOMER_TIER_CHANGED",
		20: "EVENT_TYPE_ORDER_CREATED",
		21: "EVENT_TYPE_ORDER_PAID",
		22: "EVENT_TYPE_ORDER_FULFILLED",
		23: "EVENT_TYPE_ORDER_CANCELLED",
		24: "EVENT_TYPE_REFUND_CREATED",
		25: "EVENT_TYPE_CHECKOUT_STARTED",
		26: "EVENT_TYPE_PRODUCT_UPDATED",
		30: "EVENT_TYPE_CARING_ACTION_SENT",
		31: "EVENT_TYPE_CARING_ACTION_DELIVERED",
		32: "EVENT_TYPE_CARING_ACTION_READ",
		33: "EVENT_TYPE_SENTIMENT_RECORDED",
		40: "EVENT_TYPE_APPOINTMENT_CREATED",
		41: "EVENT_TYPE_APPOINTMENT_CONFIRMED",
		42: "EVENT_TYPE_APPOINTMENT_COMPLETED",
		43: "EVENT_TYPE_APPOINTMENT_CANCELLED",
		44: "EVENT_TYPE_REVIEW_SUBMITTED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":             0,
		"EVENT_TYPE_READING_COMPLETED":       1,
		"EVENT_TYPE_READING_FEEDBACK":        2,
		"EVENT_TYPE_CRISIS_DETECTED":         3,
		"EVENT_TYPE_CUSTOMER_CREATED":        10,
		"EVENT_TYPE_CUSTOMER_UPDATED":        11,
		"EVENT_TYPE_CUSTOMER_TIER_CHANGED":   12,
		"EVENT_TYPE_ORDER_CREATED":           20,
		"EVENT_TYPE_ORDER_PAID":              21,
		"EVENT_TYPE_ORDER_FULFILLED":         22,
		"EVENT_TYPE_ORDER_CANCELLED":         23,
		"EVENT_TYPE_REFUND_CREATED":          24,
		"EVENT_TYPE_CHECKOUT_STARTED":        25,
		"EVENT_TYPE_PRODUCT_UPDATED":         26,
		"EVENT_TYPE_CARING_ACTION_SENT":      30,
		"EVENT_TYPE_CARING_ACTION_DELIVERED": 31,
		"EVENT_TYPE_CARING_ACTION_READ":      32,
		"EVENT_TYPE_SENTIMENT_RECORDED":      33,
		"EVENT_TYPE_APPOINTMENT_CREATED":     40,
		"EVENT_TYPE_APPOINTMENT_CONFIRMED":   41,
		"EVENT_TYPE_APPOINTMENT_COMPLETED":   42,
		"EVENT_TYPE_APPOINTMENT_CANCELLED":   43,
		"EVENT_TYPE_REVIEW_SUBMITTED":        44,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_v1_event_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_events_v1_event_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // UUID
	EventType EventType              `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=events.v1.EventType" json:"event_type,omitempty"`
	Source    string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`   // "tarot-reading" | "customer-mgmt" | "caring" | "shop" | "scheduler"
	Version   string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"` // "1.0"
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Event payload (JSON-like structure for flexibility)
	Data *structpb.Struct `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// Tracing metadata
	Metadata      *EventMetadata `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_events_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetMetadata() *EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EventMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Request chain correlation
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                   // OpenTelemetry trace ID
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`          // Affected customer (for routing)
	ActorId       string                 `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`                   // Who triggered the event
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMetadata) Reset() {
	*x = EventMetadata{}
	mi := &file_events_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMetadata) ProtoMessage() {}

func (x *EventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMetadata.ProtoReflect.Descriptor instead.
func (*EventMetadata) Descriptor() ([]byte, []int) {
	return file_events_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventMetadata) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EventMetadata) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *EventMetadata) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *EventMetadata) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

var File_events_v1_event_proto protoreflect.FileDescriptor

const file_events_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x15events/v1/event.proto\x12\tevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa6\x02\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x123\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x14.events.v1.EventTypeR\teventType\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04data\x124\n" +
	"\bmetadata\x18\a \x01(\v2\x18.events.v1.EventMetadataR\bmetadata\"\x8d\x01\n" +
	"\rEventMetadata\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId*\x93\x06\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cEVENT_TYPE_READING_COMPLETED\x10\x01\x12\x1f\n" +
	"\x1bEVENT_TYPE_READING_FEEDBACK\x10\x02\x12\x1e\n" +
	"\x1aEVENT_TYPE_CRISIS_DETECTED\x10\x03\x12\x1f\n" +
	"\x1bEVENT_TYPE_CUSTOMER_CREATED\x10\n" +
	"\x12\x1f\n" +
	"\x1bEVENT_TYPE_CUSTOMER_UPDATED\x10\v\x12$\n" +
	" EVENT_TYPE_CUSTOMER_TIER_CHANGED\x10\f\x12\x1c\n" +
	"\x18EVENT_TYPE_ORDER_CREATED\x10\x14\x12\x19\n" +
	"\x15EVENT_TYPE_ORDER_PAID\x10\x15\x12\x1e\n" +
	"\x1aEVENT_TYPE_ORDER_FULFILLED\x10\x16\x12\x1e\n" +
	"\x1aEVENT_TYPE_ORDER_CANCELLED\x10\x17\x12\x1d\n" +
	"\x19EVENT_TYPE_REFUND_CREATED\x10\x18\x12\x1f\n" +
	"\x1bEVENT_TYPE_CHECKOUT_STARTED\x10\x19\x12\x1e\n" +
	"\x1aEVENT_TYPE_PRODUCT_UPDATED\x10\x1a\x12!\n" +
	"\x1dEVENT_TYPE_CARING_ACTION_SENT\x10\x1e\x12&\n" +
	"\"EVENT_TYPE_CARING_ACTION_DELIVERED\x10\x1f\x12!\n" +
	"\x1dEVENT_TYPE_CARING_ACTION_READ\x10 \x12!\n" +
	"\x1dEVENT_TYPE_SENTIMENT_RECORDED\x10!\x12\"\n" +
	"\x1eEVENT_TYPE_APPOINTMENT_CREATED\x10(\x12$\n" +
	" EVENT_TYPE_APPOINTMENT_CONFIRMED\x10)\x12$\n" +
	" EVENT_TYPE_APPOINTMENT_COMPLETED\x10*\x12$\n" +
	" EVENT_TYPE_APPOINTMENT_CANCELLED\x10+\x12\x1f\n" +
	"\x1bEVENT_TYPE_REVIEW_SUBMITTED\x10,B\x9b\x01\n" +
	"\rcom.events.v1B\n" +
	"EventProtoP\x01Z9github.com/tarotfriend/platform/gen/go/events/v1;eventsv1\xa2\x02\x03EXX\xaa\x02\tEvents.V1\xca\x02\tEvents\\V1\xe2\x02\x15Events\\V1\\GPBMetadata\xea\x02\n" +
	"Events::V1b\x06proto3"

var (
	file_events_v1_event_proto_rawDescOnce sync.Once
	file_events_v1_event_proto_rawDescData []byte
)

func file_events_v1_event_proto_rawDescGZIP() []byte {
	file_events_v1_event_proto_rawDescOnce.Do(func() {
		file_events_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_event_proto_rawDesc), len(file_events_v1_event_proto_rawDesc)))
	})
	return file_events_v1_event_proto_rawDescData
}

var file_events_v1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_v1_event_proto_goTypes = []any{
	(EventType)(0),                // 0: events.v1.EventType
	(*Event)(nil),                 // 1: events.v1.Event
	(*EventMetadata)(nil),         // 2: events.v1.EventMetadata
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
}
var file_events_v1_event_proto_depIdxs = []int32{
	0, // 0: events.v1.Event.event_type:type_name -> events.v1.EventType
	3, // 1: events.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	4, // 2: events.v1.Event.data:type_name -> google.protobuf.Struct
	2, // 3: events.v1.Event.metadata:type_name -> events.v1.EventMetadata
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_events_v1_event_proto_init() }
func file_events_v1_event_proto_init() {
	if File_events_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_event_proto_rawDesc), len(file_events_v1_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_event_proto_goTypes,
		DependencyIndexes: file_events_v1_event_proto_depIdxs,
		EnumInfos:         file_events_v1_event_proto_enumTypes,
		MessageInfos:      file_events_v1_event_proto_msgTypes,
	}.Build()
	File_events_v1_event_proto = out.File
	file_events_v1_event_proto_goTypes = nil
	file_events_v1_event_proto_depIdxs = nil
}
